package com.xzit.model;

import java.math.BigDecimal;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.name
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.addr
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.age
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.job
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.sal
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    private BigDecimal sal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.name
     *
     * @return the value of employees.name
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.name
     *
     * @param name the value for employees.name
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.addr
     *
     * @return the value of employees.addr
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.addr
     *
     * @param addr the value for employees.addr
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.age
     *
     * @return the value of employees.age
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.age
     *
     * @param age the value for employees.age
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.job
     *
     * @return the value of employees.job
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.job
     *
     * @param job the value for employees.job
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.sal
     *
     * @return the value of employees.sal
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public BigDecimal getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.sal
     *
     * @param sal the value for employees.sal
     *
     * @mbg.generated Sun Mar 15 15:55:30 CST 2026
     */
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }
}